version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ss0rd
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080" # Exposes Adminer on port 8080
    networks:
      - app_network

  api:
    image: bookreservation-system/bookreservation-system-api:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"        # Port for accessing the Portainer UI
      - "9443:9443"        # Port for accessing the Portainer HTTPS interface (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Portainer to manage the Docker daemon
      - portainer_data:/data                          # Persist Portainer data
    restart: unless-stopped

volumes:
  postgres-data:
  portainer_data:

networks:
  app_network:
    driver: bridge
